site_name: ThreeThirds Collaboration Docs
site_description: ThreeThirds Collaboration Documentation
site_author: Jared Roberts
site_url: https://docs.collab.cloud
repo_url: https://collab.cloud
repo_name: collab.cloud

theme:
  name: material
  features:
    - tabs
  palette:
    primary: cyan
    accent: grey
  favicon: assets/images/favicon.png
#  logo: assets/images/logo.svg

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/collabdotcloud
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/3thirdscollab
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/threethirds-hcl-cloud-hosting

nav:
  - Home: index.md
  - Getting Started: getting-started-new.md
  - Migration from IBM SmartCloud: ibm-migration.md

  - Admin Documentation:
    - Administration:
      - Manage Organisation: admin/admin-org.md
#      - Connections: admin/
#      - Mail: admin/
      - Sametime: admin/admin-sametime.md
      - Connections API: admin/api-clients.md
    - Authentication:
      - Federated Identity Authentication with SAML: admin/auth-saml.md
    - Extensions:
      - WebEx: admin/extension-webex.md
#    - Customizing: admin/

  - User Documentation:
#    - Using Mail:
#      - Getting Started: users/using-mail-gettingstarted.md
#      - Using Mail & Verse: users/using-mail-verse.md
    - Using Connections:
      - Getting Started: users/using-connections-gettingstarted.md
      - Extensions:
        - WebEx: users/using-webex-extension.md
        - Desktop Sync for Mac: users/desktop-plugins-mac.md
        - Desktop Plug-ins for Windows: users/desktop-plugins-windows.md
      - Connections Mobile App: users/connections-mobile-app.md
      - External users: users/connections-external-users.md
    - Using Sametime:
      - Getting Started: users/using-sametime-gettingstarted.md
      - Using Sametime: users/using-sametime.md
    - Using Activities Plus:
      - Getting Started: users/aplus-gettingstarted.md
      - For Users: users/aplus-for-users.md
      - For Community Managers: users/aplus-for-comm-managers.md
      - Tips And Tricks: users/aplus-tips-and-tricks.md
      - Activities Plus Mobile App: users/aplus-mobile-app.md

  - Help:
    - Troubleshooting & Support: help/troubleshooting-support.md
    - Downloads: help/downloads.md
    - Known Issues: help/known-issues.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

extra_css:
  - "/assets/css/custom.css"

#google_analytics:
#  - "INSERT CODE FROM GOOGLE SITE ADMIN"
#  - "auto"
