site_name: ThreeThirds Collaboration Docs
site_description: ThreeThirds Collaboration Documentation
site_author: Jared Roberts
site_url: https://docs.collab.cloud
repo_url: https://collab.cloud
repo_name: collab.cloud

theme:
  name: material
  features:
    - tabs
  palette:
    primary: red
    accent: orange
  favicon: assets/images/favicon.png
#  logo: assets/images/logo.svg

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/collabdotcloud
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/3thirdscollab
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/threethirds-hcl-cloud-hosting

nav:
  - Home: index.md
  - Getting Started:
    - New Customer: new-customer.md
    - What's New: whats-new.md
    - Migration from IBM SmartCloud: admin/ibm-migration.md
#  - Admin Documentation:
#    - Administering Mail:
#      - User Management: admin/usermanage-mail.md
#      - Mail Mobile: admin/admin-mail-mobile.md
#    - Administering Connections:
#      - User Management: admin/usermanage-connections.md
#      - Connections Mobile: admin/admin-connections-mobile.md
#    - Customizing: admin/admindummypage.md
#    - Security: admin/admindummypage.md
  - User Documentation:
#    - Using Mail:
#      - Getting Started: users/using-mail-gettingstarted.md
#      - Using Mail & Verse: users/using-mail-verse.md
    - Using Connections:
      - Getting Started: users/using-connections-gettingstarted.md
      - Desktop Sync for Mac: users/desktop-plugins-mac.md
      - Desktop Plug-ins for Windows: users/desktop-plugins-windows.md
#      - Using Connections: users/using-connections.md
    - Using Sametime:
      - Getting Started: users/using-sametime-gettingstarted.md
      - Using Sametime: users/using-sametime.md
  - Help:
    - Troubleshooting & Support: help/troubleshooting-support.md
    - Downloads: help/downloads.md
    - Contributing: help/contributing.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

extra_css:
  - "/assets/css/custom.css"

#google_analytics:
#  - "INSERT CODE FROM GOOGLE SITE ADMIN"
#  - "auto"
